"""
Synthetic data generation using external APIs (OpenAI, Anthropic, etc.).

Generates high-quality training examples using LLMs, with cost tracking and budget management.
"""

from typing import List, Dict, Optional
import logging
import time
from pathlib import Path

from .base import DataGeneratorPlugin

logger = logging.getLogger(__name__)


class SyntheticAPIGenerator(DataGeneratorPlugin):
    """
    Generate synthetic training data using external LLM APIs.

    Supports:
    - OpenAI (GPT-4, GPT-3.5)
    - Anthropic (Claude)
    - Cost tracking and budget limits
    - Rate limiting
    """

    # Pricing per 1K tokens (as of 2024)
    PRICING = {
        'openai': {
            'gpt-4': {'input': 0.03, 'output': 0.06},
            'gpt-4-turbo': {'input': 0.01, 'output': 0.03},
            'gpt-3.5-turbo': {'input': 0.001, 'output': 0.002},
        },
        'anthropic': {
            'claude-3-opus': {'input': 0.015, 'output': 0.075},
            'claude-3-sonnet': {'input': 0.003, 'output': 0.015},
            'claude-3-haiku': {'input': 0.00025, 'output': 0.00125},
        }
    }

    def __init__(self, config: Dict):
        super().__init__(config)

        api_config = config.get('synthetic_api', {})

        # API configuration
        self.provider = api_config.get('provider', 'openai')  # openai or anthropic
        self.model = api_config.get('model', 'gpt-3.5-turbo')
        self.api_key = api_config.get('api_key')
        self.budget_usd = api_config.get('budget_usd', 10.0)

        # Generation parameters
        self.examples_per_file = api_config.get('examples_per_file', 5)
        self.temperature = api_config.get('temperature', 0.7)
        self.max_tokens = api_config.get('max_tokens', 1000)

        # Rate limiting
        self.requests_per_minute = api_config.get('requests_per_minute', 10)
        self.last_request_time = 0

        # Cost tracking
        self.total_cost = 0.0
        self.budget_exceeded = False

        # Client initialization (lazy)
        self._client = None

        if not self.api_key:
            logger.warning(
                f"No API key provided for {self.provider}. "
                "Synthetic generation will be disabled."
            )

    def generate(self, code_sample: Dict) -> List[Dict]:
        """
        Generate synthetic training examples for a code sample.

        Args:
            code_sample: Code sample with parsed structure

        Returns:
            List of training examples generated by LLM
        """
        if not self.api_key:
            logger.warning("No API key - skipping synthetic generation")
            return []

        if self.budget_exceeded:
            logger.warning(
                f"Budget exceeded (${self.budget_usd:.2f}) - skipping synthetic generation"
            )
            return []

        examples = []

        try:
            # Extract relevant code information
            file_path = code_sample.get('file_path', '')
            content = code_sample.get('content', '')
            parsed = code_sample.get('parsed', {})

            # Generate different types of examples
            example_types = [
                self._generate_debugging_examples,
                self._generate_explanation_examples,
                self._generate_refactoring_examples,
                self._generate_qa_examples,
            ]

            for generate_func in example_types:
                if self.budget_exceeded:
                    break

                try:
                    generated = generate_func(code_sample)
                    examples.extend(generated)
                except Exception as e:
                    logger.error(f"Error in {generate_func.__name__}: {e}")

            self.examples_generated += len(examples)
            return examples

        except Exception as e:
            logger.error(f"Error generating synthetic examples: {e}", exc_info=True)
            return []

    def _generate_debugging_examples(self, code_sample: Dict) -> List[Dict]:
        """Generate debugging scenarios from code."""
        examples = []

        functions = code_sample.get('parsed', {}).get('functions', [])
        if not functions:
            return examples

        # Pick a function to create debugging example
        func = functions[0]  # For now, just use first function

        prompt = f"""
Given this code:
```python
{func.get('body', '')}
```

Generate a realistic bug scenario and its fix.

Format:
1. BUGGY VERSION: The code with a subtle bug
2. ERROR MESSAGE: What error this causes
3. EXPLANATION: Why this is a bug
4. FIXED VERSION: The corrected code
"""

        response = self._call_api(prompt)
        if response:
            examples.append({
                'instruction': 'Debug and fix this code:',
                'input': response.get('buggy_version', ''),
                'output': response.get('fixed_version', ''),
                'metadata': {
                    'type': 'debugging',
                    'file_path': code_sample.get('file_path'),
                }
            })

        return examples

    def _generate_explanation_examples(self, code_sample: Dict) -> List[Dict]:
        """Generate code explanation examples."""
        examples = []

        content = code_sample.get('content', '')
        if not content or len(content) < 100:
            return examples

        prompt = f"""
Analyze this code and provide a detailed explanation:

```python
{content[:1000]}  # Limit to avoid huge prompts
```

Explain:
1. What this code does
2. Key functions and their purpose
3. Important patterns or techniques used
4. Potential improvements
"""

        response = self._call_api(prompt)
        if response:
            examples.append({
                'instruction': 'Explain what this code does:',
                'input': content[:500],
                'output': response.get('explanation', ''),
                'metadata': {
                    'type': 'explanation',
                    'file_path': code_sample.get('file_path'),
                }
            })

        return examples

    def _generate_refactoring_examples(self, code_sample: Dict) -> List[Dict]:
        """Generate refactoring examples."""
        examples = []

        functions = code_sample.get('parsed', {}).get('functions', [])
        if not functions:
            return examples

        func = functions[0]

        prompt = f"""
Refactor this code to improve it:

```python
{func.get('body', '')}
```

Provide:
1. ORIGINAL: The original code
2. REFACTORED: Improved version
3. IMPROVEMENTS: List of improvements made
"""

        response = self._call_api(prompt)
        if response:
            examples.append({
                'instruction': 'Refactor this code to improve quality:',
                'input': func.get('body', ''),
                'output': response.get('refactored', ''),
                'metadata': {
                    'type': 'refactoring',
                    'file_path': code_sample.get('file_path'),
                }
            })

        return examples

    def _generate_qa_examples(self, code_sample: Dict) -> List[Dict]:
        """Generate Q&A pairs about the code."""
        examples = []

        content = code_sample.get('content', '')
        if not content:
            return examples

        prompt = f"""
Generate 3 questions and answers about this code:

```python
{content[:800]}
```

Format:
Q1: [Question about code purpose]
A1: [Detailed answer]

Q2: [Question about specific function]
A2: [Detailed answer]

Q3: [Question about usage/example]
A3: [Detailed answer]
"""

        response = self._call_api(prompt)
        if response:
            # Parse Q&A pairs
            qa_text = response.get('qa', '')
            if qa_text:
                examples.append({
                    'instruction': 'Answer questions about this code:',
                    'input': qa_text,
                    'output': '',
                    'metadata': {
                        'type': 'qa',
                        'file_path': code_sample.get('file_path'),
                    }
                })

        return examples

    def _call_api(self, prompt: str) -> Optional[Dict]:
        """
        Call the configured LLM API.

        Args:
            prompt: The prompt to send

        Returns:
            Parsed response or None if error
        """
        # Check budget
        if self.total_cost >= self.budget_usd:
            self.budget_exceeded = True
            logger.warning(f"Budget exceeded: ${self.total_cost:.2f} >= ${self.budget_usd:.2f}")
            return None

        # Rate limiting
        self._enforce_rate_limit()

        try:
            if self.provider == 'openai':
                return self._call_openai(prompt)
            elif self.provider == 'anthropic':
                return self._call_anthropic(prompt)
            else:
                logger.error(f"Unknown provider: {self.provider}")
                return None
        except Exception as e:
            logger.error(f"API call failed: {e}", exc_info=True)
            return None

    def _call_openai(self, prompt: str) -> Optional[Dict]:
        """Call OpenAI API."""
        try:
            import openai
        except ImportError:
            logger.error("openai package not installed. Run: pip install openai")
            return None

        if not self._client:
            self._client = openai.OpenAI(api_key=self.api_key)

        try:
            response = self._client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are an expert code teacher and debugger."},
                    {"role": "user", "content": prompt}
                ],
                temperature=self.temperature,
                max_tokens=self.max_tokens,
            )

            # Track cost
            usage = response.usage
            cost = self._calculate_cost(
                usage.prompt_tokens,
                usage.completion_tokens,
                'openai',
                self.model
            )
            self.total_cost += cost

            # Extract response
            content = response.choices[0].message.content
            return {'response': content}

        except Exception as e:
            logger.error(f"OpenAI API error: {e}")
            return None

    def _call_anthropic(self, prompt: str) -> Optional[Dict]:
        """Call Anthropic API."""
        try:
            import anthropic
        except ImportError:
            logger.error("anthropic package not installed. Run: pip install anthropic")
            return None

        if not self._client:
            self._client = anthropic.Anthropic(api_key=self.api_key)

        try:
            response = self._client.messages.create(
                model=self.model,
                max_tokens=self.max_tokens,
                temperature=self.temperature,
                messages=[
                    {"role": "user", "content": prompt}
                ]
            )

            # Track cost (approximate - Anthropic doesn't always return token counts)
            # Estimate: ~4 chars per token
            input_tokens = len(prompt) // 4
            output_tokens = len(response.content[0].text) // 4

            cost = self._calculate_cost(
                input_tokens,
                output_tokens,
                'anthropic',
                self.model
            )
            self.total_cost += cost

            # Extract response
            content = response.content[0].text
            return {'response': content}

        except Exception as e:
            logger.error(f"Anthropic API error: {e}")
            return None

    def _calculate_cost(
        self,
        input_tokens: int,
        output_tokens: int,
        provider: str,
        model: str
    ) -> float:
        """Calculate cost for API call."""
        pricing = self.PRICING.get(provider, {}).get(model)
        if not pricing:
            logger.warning(f"No pricing for {provider}/{model}, using estimate")
            return 0.01  # Conservative estimate

        input_cost = (input_tokens / 1000) * pricing['input']
        output_cost = (output_tokens / 1000) * pricing['output']

        return input_cost + output_cost

    def _enforce_rate_limit(self):
        """Enforce rate limiting between API calls."""
        if self.requests_per_minute <= 0:
            return

        min_interval = 60.0 / self.requests_per_minute
        elapsed = time.time() - self.last_request_time

        if elapsed < min_interval:
            sleep_time = min_interval - elapsed
            logger.debug(f"Rate limiting: sleeping {sleep_time:.2f}s")
            time.sleep(sleep_time)

        self.last_request_time = time.time()

    def estimate_cost(self, num_files: int) -> float:
        """
        Estimate cost for processing given number of files.

        Args:
            num_files: Number of code files

        Returns:
            Estimated cost in USD
        """
        # Rough estimate:
        # - Average file: 200 lines = ~1000 tokens
        # - Generate 5 examples per file
        # - Each generation: 1000 input + 500 output tokens

        avg_input_tokens = 1000
        avg_output_tokens = 500

        pricing = self.PRICING.get(self.provider, {}).get(self.model)
        if not pricing:
            return num_files * 0.05  # Conservative fallback

        cost_per_file = (
            (avg_input_tokens / 1000) * pricing['input'] +
            (avg_output_tokens / 1000) * pricing['output']
        ) * self.examples_per_file

        return cost_per_file * num_files

    def get_stats(self) -> Dict:
        """Get generation statistics including cost."""
        stats = super().get_stats()
        stats.update({
            'provider': self.provider,
            'model': self.model,
            'budget_usd': self.budget_usd,
            'budget_remaining_usd': max(0, self.budget_usd - self.total_cost),
            'budget_exceeded': self.budget_exceeded,
        })
        return stats
